# Spring Datasource Config
spring.datasource.url=jdbc:postgresql://localhost:5432/codeanalyzer

spring.datasource.username=CodeAnalyzer
spring.datasource.password=Apple@123
# Kafka Bootstrap servers
spring.kafka.bootstrap-servers=localhost:9092
# JWT Secret (replace with your secret key)
# security.jwt.secret=8F$3m!Xp9Q2@ZwlT#Jr7UyV6&CsXePm
security.jwt.secret=1BLhN7LE+JQou4xNcgok8siIJos5LaUE1yfPgySuG7s=
# Server port
server.port=8080

spring.main.allow-bean-definition-overriding=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=code-analyzer-group
spring.kafka.consumer.auto-offset-reset=earliest

# Enable these lines if you want to specify serializers/deserializers explicitly
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.LongDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.LongSerializer




