# Spring Datasource Config
spring.datasource.url=jdbc:postgresql://localhost:5432/codeanalyzer

spring.datasource.username=CodeAnalyzer
spring.datasource.password=Apple@123
# Kafka Bootstrap servers
spring.kafka.bootstrap-servers=localhost:9092
# JWT Secret (replace with your secret key)
security.jwt.secret=8F$3m!Xp9Q2@ZwlT#Jr7UyV6&CsXePm

# Server port
server.port=8080

spring.main.allow-bean-definition-overriding=true

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG


